### PR TITLE
Add globbing support in check-file-exists.rb to display all offending…

### PR DESCRIPTION
**Pull request by Evesy**
… files

## Pull Request Checklist

In reference to: #17 

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] Existing tests pass 

#### Purpose

Adding proper globbing support in this check will allow the output to display more useful information to the end user:

- Full list of all offending files
- Count of offending files

#### Known Compatablity Issues

No compatibility issues with previous versions.

### CODE REVIEW

**Comment by Evesy** [comment]
Build is failing on 1.9.3 with some encoding errors that I can't quite track down.

I'd be happy to drop support for Ruby 1.9 if the feeling is that it's the right thing to do, however I'd also like to try and get it fixed.

**Comment by majormoses** [comment]
We no longer support 1.9 so I am all for dropping support which makes this a breaking change which needs to be called out in the changelog.

**Review by majormoses — APPROVED** [review]
LGTM

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-filesystem-checks/versions/1.0.0

**Pull request merged**
